### ISSUE TITLE
Fails to read files in folders named with Korean characters

### ISSUE THREAD

**Issue by pPkMnh4to8994h** [Acro748/SkyrimPluginEditor#1]
If you try to load a mod folder that has subfolders or files with Korean letters, the program will be unable to read them.
![image](https://github.com/user-attachments/assets/aca5b8b7-acff-4fa7-bcdc-ef8d766a6eed)

Renaming these fixes the issue.

**Comment by Acro748** [comment]
well, it seems not caused by korean word
make sure that file is still open well in nifskope
if doesn't open with nifskope then it cause by wrong nif file 
if open well, it caused by an access error due to there a program already using that nif file
